### ISSUE TITLE
Focal BEC Unit Functionality

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#18]
At this stage, we have hover-over identification of BEC units. We need an additional functionality where we click on a unit to select it as the "focal BEC unit". This will be a map polygon and scatterplot point that stays highlighted, allowing the user to hover over other "comparison BEC units". 

in the scatter plot: if climate change trajectory is toggled on, the focal unit will have a trajectory that stays plotted, while the comparison unit has a trajectory only as long as it is hovered over. 
![fullsizerender](https://cloud.githubusercontent.com/assets/17104005/16056039/9856c392-3228-11e6-8d5a-5e7f04662477.jpg)

In the time series plot, the comparison unit would be plotted as a second time series. 

at the top left, it might be good to explicitly identify the focal and comparison units. ideally both can be selected by dropdown in addition to on the map and scatterplot (e.g. for a user who wants to know about the unit but doesn't know where it is on the map or scatterplot.)

**Comment by joeyklee** [comment]
see scatterplot :)
