### ISSUE TITLE
Managing climate variables

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#19]
At this stage of development we are only working with four climate variables. However, the final product will need to support dozens of climate variables (hundreds are available in ClimateBC). we need to think about how to do this and what the limits are. 

One approach to reducing the numbers of climate variables in a dropdown list is to split the variables up into different categories. so selection of variables would go in three dropdowns: category (annual, seasonal, monthly, BIOCLIM); x variable; y variable.  the x and y dropdown lists would change dependent on the category. 

There are several different schemes for categorizing climate variables: 

From ClimateBC: 
- Annual bioclimatic variables (MAT, MAP, AHM, SHM, BFFP, etc.)
- Seasonal bioclimatic variables (Tmin, Tmax, PAS, etc. for wt, sp, sm, at)
- monthly basic variables (Tmin, Tmax, PPT for months 01, 02, 03,... 12)

Other schemes
- [BIOCLIM ](http://www.worldclim.org/bioclim)

We also need to provide full names of each climate variable (e.g., PAS = precipitation as snow). that's a task for me (colin)

**Comment by cmahony** [comment]
i created a lookup table for all of the 213 ClimateBC variables that we could possibly use. it includes a long name, time unit, and category for each variable code. 

i uploaded it to the repository: bec-explorer/data/ClimateData/Variables_ClimateBC.csv

I compiled this table based on the information provided [here](http://www.climatewna.com/help%5CclimateBC%5Chelp.htm#_Toc410137602).

**Comment by joeyklee** [comment]
thanks colin! I will take a look in a bit. (I'm spending a bit of time on the interface interactions this afternoon)

**Comment by cmahony** [comment]
i created a lookup table for all of the 213 ClimateBC variables that we could possibly use. it includes a long name, time unit, category, and default scale (raw vs. logarithmic) for each variable code. 
I compiled this table based on the information provided [here](http://www.climatewna.com/help%5CclimateBC%5Chelp.htm#_Toc410137602).

**Comment by joeyklee** [comment]
Nice - I just wrote a function to add in all the columns from the data table to the climate variables selection box. Next step will be to select out only the variables we want and then prettify the names

**Comment by joeyklee** [comment]
see current dropdown selection :)
