### ISSUE TITLE
Scatterplot showing a small subset of units

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#21]
The scatterplot is only showing about 40 of the 200+ bec units. the ones that are showing up are the units whose BGC_LABEL has no spaces. Once the primary field is changed to MAP_LABEL, this problem might go away.

**Comment by cmahony** [comment]
yes, the data file for the scatterplot has BEC unit codes that are based on MAP_LABEL, but the tool is using BGC_LABEL as a lookup field. once this is fixed so that all lookups are done with MAP_LABEL, then the problem with the scatterplot will go away.

**Comment by joeyklee** [comment]
I changed all of the `bgc_label` to `map_label` but it seems that there may be some `NULL` values in the data table we're using for the scatter plot (https://becexplorer.cartodb.com/tables/bgcv10beta_200m_wgs84_merge) -- could be an issue with the table merging. I will look into it.

**Comment by joeyklee** [comment]
Ah-hah! I now know why the scatterplot is only showing the small selected portions. It seems that the dataset with the merged climate variables is simply missing the other regions for some reason. See:

<img width="1507" alt="screen shot 2016-06-24 at 12 55 05 pm" src="https://cloud.githubusercontent.com/assets/3622055/16349036/15281332-3a0b-11e6-8ef5-a0a6ff948c24.png">

We will need to resolve this by merging in the data correctly

**Comment by joeyklee** [comment]
This issue is now fixed with the correct data merge method - using the column join rather than spatial join in cartodb on the field "map_label" (for the geometry layer) and the "id2" (for the csv data)
