### ISSUE TITLE
Redesign UI + refactor codebase

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#22]
Currently working on redesign of UI based on Materialize (http://materializecss.com/) - prototype after day 1 - finding the accordion to be really helpful re screen space... also I never thought I'd be into the drop shadow stuff, but it adds some nice texture :) : 

![screen shot 2016-06-14 at 11 14 15 pm](https://cloud.githubusercontent.com/assets/3622055/16069867/8ddb6162-3286-11e6-9032-6d266613782c.png)

**Comment by joeyklee** [comment]
Still working on the refactoring, but things are coming together. I decided to start building our application with server side capabilities using node.js, so I will have to deploy it (probably using heroku which is a platform as a service). Once I've got more of the functionality going, I'll push it up to the heroku server. You can see the progress in the dev-refactoring branch.

![screen shot 2016-06-16 at 12 24 18 am](https://cloud.githubusercontent.com/assets/3622055/16108617/1587d654-3359-11e6-92c3-5c4a0ec7ed3c.png)
![screen shot 2016-06-16 at 12 24 56 am](https://cloud.githubusercontent.com/assets/3622055/16108618/16f29f56-3359-11e6-94d2-97398b94445d.png)

**Comment by joeyklee** [comment]
the full screen looks really nice :) : 
![screen shot 2016-06-16 at 12 28 37 am](https://cloud.githubusercontent.com/assets/3622055/16108662/634e7366-3359-11e6-858f-eceb9b55ea0a.png)

**Comment by cmahony** [comment]
oh wow. that's looking awesome!

**Comment by joeyklee** [comment]
Our app is now available at: http://www.bec-explorer.org/ 🎉
