### ISSUE TITLE
2nd-gen wireframe

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#28]
I've thought through a modification of the current page layout that makes sense to me. The logic of this layout is that the information displayed on the page is essentially defined by two user-selected things: the focal unit and the climate variable. putting these at the top left in a control box emphases their centrality to the tool and makes it easy to change them. the control box also allows selection of the comparison bec unit (which is also controlled by hover-over on the map) and the climate change scenario (RCP4.5 or 8.5). the climate variable selected in the control box determines the x-axis of the scatterplot, the y-axis of the time series, and the color theming of the map. 

The climate variable is split into two items: the **element** (temperature, precipitation, frost-free days, etc) and the **time of year** (annual, seasonal (winter spring summer fall), and monthly (jan feb mar...). the reasons for doing it this way are: (1) it greatly reduces the length of the dropdowns, and (2) it facilitates the annual cycle graph, which shows the selected element at several times of year. Note that a handful of climate variables are only relevant at the annual timescale (e.g. bffp, beginning of the frost free period): time of year would be limited to "annual" for these climate variables. 

i put the color theming selection box in the map itself. i imagine the dropdown boxes would retract once selections are complete so that they only take up a single line and do not obscure the map. 

As for the log-transformation option, i'm thinking that for the moment we should have this hardwired and not user-specified. the default expression (log or raw) is specified in the variable names lookup table that i put on the repo. 

![wireframe_annotated](https://cloud.githubusercontent.com/assets/17104005/16209828/b59c1f50-36ed-11e6-8421-12d0bc4f4c39.jpg)

**Comment by joeyklee** [comment]
wow! brilliant! this is really really great ❤️❤️❤️❤️👏👏👏👏👏. I will work on this as the design standard and do my best to match it / modify it for the cleanest experience :) 

thanks so much @cmahony!

**Comment by joeyklee** [comment]
@cmahony - for the scatterplot: when a user selects varying time ranges, how do we show the variable of interest? I would assume that we would show an average of the data per variable across the years selected. 

for example: if a user selects 2011 - 2013, then the scatterplot would show the average of the X-variable selected and the average of the y-variable selected. 

<img width="1507" alt="screen shot 2016-06-29 at 12 15 57 pm" src="https://cloud.githubusercontent.com/assets/3622055/16465497/eecdf34a-3df3-11e6-963a-bd183b3a0d7a.png">

**Comment by joeyklee** [comment]
BC - climate explorer is getting a makeover - will be much better IMHO:

![screen shot 2016-07-02 at 1 07 52 am](https://cloud.githubusercontent.com/assets/3622055/16539225/83c47e02-3ff1-11e6-90f2-53a9f9e2c7df.png)

**Comment by joeyklee** [comment]
The latest is up: http://www.bc-climate-explorer.org/

**Comment by joeyklee** [comment]
I will close this issue for now as we have the major features now implemented
