### ISSUE TITLE
Full Climate data files

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#29]
@joeyklee , 
I've put the final data set up on the dropbox folder. 
There are quite a few files, but I think the key one you are using right now is the BEC10centroid_Normal_1971_2000MSY.csv. 

The other files are: 
- historical time series (BEC10centroid_1901-2014MSYT.csv)
- projected normals for 15 GCMs, 2 RCPs, and 3 time periods (BEC10centroid_99GCMs_MSYT.csv)
- other historical normals and decadal data (e.g. BEC10centroid_Normal_1951_1980MSY.csv)
- I have also generated a bunch of projected time series data, but it's a lot of data and I'm going to work with it for a bit before uploading it... perhaps boil it down a bit. 

I have kept the data files in the raw ClimateBC output format, so that we can easily switch out data sets without requiring a middleman. 

I've uploaded a Variables_ClimateBC_revised.csv to the repo. I've reduced it so that it just has the climate elements (e.g. Tmin, PPT) and not the time scales (e.g. _wt, _sp, _01(jan), _02(feb), etc.). The field "time-scalable" indicates whether there are monthly and seasonal values of the element ("yes"), or if it is just annual ("no"). The field "type" indicates whether the element is calculated from raw daily data ("Raw") or estimated from monthly data ("Derived"). Ideally, our dropdown would separate the two types and indicate whether the elements are raw or derived. The field "order" indicates the order that the elements should be displayed in the dropdown.

**Comment by cmahony** [comment]
I uploaded the projected time series for the six models as well. (to dropbox)

**Comment by joeyklee** [comment]
thanks! will get a fresh start with things tomorrow! 💪

**Comment by joeyklee** [comment]
@cmahony - just noticed that the tables are structured with "year" as a column, repeated for each year and bec unit. For our data we would instead need to have the table structured like:

| Bec unit | dd_1901 | dd_1902 | dd_1903 | rh_1901 | rh_1902 | rh_1902 |
| --- | --- | --- | --- | --- | --- | --- |
| YYYzzjj1 | X | Y | Z | ... | ... | ... |
| YYYzzjj2 | X | Y | Z | ... | ... | ... |
| YYYzzjj3 | X | Y | Z | ... | ... | ... |

We should only then have ~15.5K rows and all of the climate variables for each year as a column. Can you take care of this for the BEC10centroid_1901-2014MSYT.csv ?

Thanks!

**Comment by joeyklee** [comment]
Right now BEC10centroid_1901-2014MSYT.csv looks like:

<img width="895" alt="screen shot 2016-06-28 at 11 52 23 am" src="https://cloud.githubusercontent.com/assets/3622055/16428714/fda99742-3d27-11e6-8375-30f46b34638d.png">

**Comment by cmahony** [comment]
to clarify: 
currently, the table is 26k rows (234 BEC units x 114 years) and 247 columns. 
you want: 234 rows and 28k columns (247 variables x 114 years). 
is this right?

**Comment by joeyklee** [comment]
@cmahony - Yes, I think this is maybe the best way to go for now. Maybe we can test this out on 1 dataset and see how this goes. I just asked Cartodb to see if we could get some additional vector data space which would allow us to keep the data as is. The workaround would be to try and reduce the number of repeated geometries.

**Comment by cmahony** [comment]
ok will do. i have to do a daycare pickup now but will try to get you a new file this afternoon by 345pm. 
c

**Comment by cmahony** [comment]
here's a thought: i don't think we need to have monthly variables: just the annual and seasonal ones. the only thing we need monthly for is the annual cycle boxplots graph type. how about if the modified file i provide you has a reduced subset of only the annual and seasonal variables that we want to provide in the time series?

**Comment by joeyklee** [comment]
@cmahony - whichever is easiest ... I'm working with some monthly data now and it does look kind of cool, but I understand that the annual stuff is probably most relevant:

<img width="425" alt="screen shot 2016-06-28 at 1 15 20 pm" src="https://cloud.githubusercontent.com/assets/3622055/16430824/74afa49e-3d32-11e6-9093-95a79f22aaed.png">

**Comment by cmahony** [comment]
i'll split them: one file annual/seasonal for the time series plots, one file monthly for the annual cycle plots.

**Comment by joeyklee** [comment]
sure - then we can evaluate. Thanks!!

**Comment by cmahony** [comment]
cool graph by the way. looks like a simple way to get into annual cycle plots.

**Comment by cmahony** [comment]
v. stoked to see you working with the monthly data!!

**Comment by joeyklee** [comment]
yeah - i'm just trying to get it hooked up so that the focal and comparison selection choose the data represented in the timeseries

**Comment by cmahony** [comment]
can't wait to see focal/comparison in action. that will be a major milestone.

**Comment by cmahony** [comment]
... and you will be feted for generations as a web-mapping legend!

**Comment by joeyklee** [comment]
so it is sort of working now.. still need to fix some things, but in principle its working: 
<img width="1498" alt="screen shot 2016-06-28 at 1 32 35 pm" src="https://cloud.githubusercontent.com/assets/3622055/16431305/dadf0578-3d34-11e6-9314-8c4bf07fa8df.png">

**Comment by cmahony** [comment]
I've uploaded two new time series files to the dropbox folder. They are the BEC10centroid_1901-2014MSYT.csv file split into annual/season ("YT") and monthly ("M") variables, and transposed as requested ("_T") so that the year is in part of the variable name. 

here is the R script for this transposition: 

```
setwd("C:\\Users\\Colin\\Documents\\Masters\\Research\\Data\\ClimateBC_v530")
X <- read.csv("BEC10centroid_1901-2014MSYT.csv")

X <- X[,-grep("Rad",names(X))] #remove crappy radiation data
X.sy <- X[,c(1:6, -grep("01|02|03|04|05|06|07|08|09|10|11|12",names(X)))] #create a annual/seasonal data set to be used for time series
X.m <- X[,c(1:6, grep("01|02|03|04|05|06|07|08|09|10|11|12",names(X)))] #create a monthly data set to be used for annual cycle plots

# change position of year from rows to columns
Y.sy <- X.sy[which(X.sy[,1]==min(unique(X.sy[,1]))),2:6]
for(i in seq(min(unique(X.sy[,1])),max(unique(X.sy[,1])))){
  temp <- X.sy[which(X.sy[,1]==i),7:length(X.sy)]
  colnames(temp) <- paste(names(temp),i,sep="_") 
  Y.sy <- cbind(Y.sy,temp)
}

Y.m <- X.m[which(X.m[,1]==min(unique(X.m[,1]))),2:6]
for(i in seq(min(unique(X.m[,1])),max(unique(X.m[,1])))){
  temp <- X.m[which(X.m[,1]==i),7:length(X.m)]
  colnames(temp) <- paste(names(temp),i,sep="_") 
  Y.m <- cbind(Y.m,temp)
}

write.csv(Y.sy, "BEC10centroid_1901-2014SYT_T.csv", row.names=FALSE)
write.csv(Y.m, "BEC10centroid_1901-2014MT_T.csv", row.names=FALSE)


```

**Comment by joeyklee** [comment]
Aw darn - looks like we can only have tables with 250 columns max. 

<img width="1507" alt="screen shot 2016-06-29 at 9 44 58 am" src="https://cloud.githubusercontent.com/assets/3622055/16460836/45a0456c-3dde-11e6-81f5-2c475e382255.png">

**Comment by joeyklee** [comment]
I'm thinking now, however that we can actually just query the table as is - the reason why the table was getting so big was because we were trying to join it with the geometries. Let me experiment with the existing large data set. Sorry to make you transpose the data!

**Comment by cmahony** [comment]
no problem, i like the idea of keeping the data in the raw climateBC output if possible, so that we can switch out data if need be, without running through an R script.
