### ISSUE TITLE
investigate topojson for spatial data compression

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#3]
https://github.com/mbostock/topojson

http://blog.thematicmapping.org/2013/06/converting-shapefiles-to-topojson.html

**Comment by joeyklee** [comment]
![screen shot 2016-06-01 at 2 57 59 pm](https://cloud.githubusercontent.com/assets/3622055/15727085/49244854-2809-11e6-949c-d03aa192930b.png)

Its mega slow - but it works. we can work on optimization and simplifying the lines / removing uneeded data columns :)!

**Comment by cmahony** [comment]
sa-weeeeeeeeet!!
