### ISSUE TITLE
Time Series Plot

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#30]
I created a few draft time series plots in R just to get used to the data and how we might lay things out. 

The components of the plot are: 
- historical time series for the focal unit (IDFxh1) and comparison unit (BGxh1)
- 1951-2000 climate average for both units, to improve readability. 
- RCP4.5 projections from the 6 climate models for which ClimateBC provides time series
- the annual average projection across the 6 climate models. 
- the scale of the y axis is determined by the min/max of both the RCP4.5 and RCP8.5 projections, so that the plot scale doesn't change when the RCP changes

a nice piece of interactive functionality would be to show the model name and highlighted time series when the line is hovered over. 

![graph_timeseries_tmin_sm_rcp45_idfxh1_bgxh1_](https://cloud.githubusercontent.com/assets/17104005/16250041/243cab8c-37cf-11e6-86ce-16936e46fa4e.png)

here is the graph for RCP8.5

![graph_timeseries_tmin_sm_rcp85_idfxh1_bgxh1_](https://cloud.githubusercontent.com/assets/17104005/16250253/cc775684-37d0-11e6-9508-1e25e71dfb87.png)

note that putting both RCPs on makes for a pretty noisy graph, but it would be nice to be able to have the other RCP as context for whatever the user has selected. i'll work on that a bit more. 

![graph_timeseries_tmin_sm_idfxh1_bgxh1_](https://cloud.githubusercontent.com/assets/17104005/16250260/d5da8f48-37d0-11e6-86e7-c24301d572d4.png)

a major problem is that ClimateBC doesn't provide the historical projection for each model. This is crazy, since all model runs start at ~1850 and are run through to 2100. the model runs don't start at 2011, as implied by the climateBC data. the outcome is that there is a lot of model spread at 2011, and people will wonder, "why all the model spread?"... this will generate no end of confusion and lashback. if i can't convince the ClimateBC folks to add the historical component of the projection, i will have to downscale some model projections myself. it will be worth it! but for the beta version, we will just go with the climateBC data. 

i also would like to evaluate the ensemble and make sure that all the models included deserve inclusion based on the most recent assessments of the CMIP5 model output.

**Comment by joeyklee** [comment]
Hi @cmahony - very cool. This is also what I imagined with regards to the projections. Right now we're using a graphing framework called [Plotly](https://plot.ly/) - I'm curious to see how far we can push it!

**Comment by joeyklee** [comment]
I'm going to close this for now as we can now map the projections for rcp 4.5 and 8.5 on the time series
