### ISSUE TITLE
Current Research Text

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#34]
@cmahony - What do you think would be appropriate to put into the "Current Research" section? (http://www.bc-climate-explorer.org/current/). 

It would be nice to have some of climate implications, etc... maybe some things highlighted using the tool?

**Comment by cmahony** [comment]
As discussed today, i will write a page describing the climate data, and another page walking the reader through some of the ways that the tool can be used to learn about climate. so instead of "current research" there will be "about climate data" and "how-to" pages
