### ISSUE TITLE
Climate Change Projections in the time series plot

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#41]
I've been thinking about how to get the most out of the time series plot. Right now, the plot shows one model projection for both RCPs and for both the focal and comparison units. A single model projection can be misleading, and the range of model projections is as important as the projections themselves. I would be great to have all 6 models for the two RCPs, but only for the focal unit. The comparison unit is simply there to provide a sense of scale for the focal unit projections. To keep the colors manageable, there would only be two colors, one for each RCP. the result will look something like this: 

![img_2448](https://cloud.githubusercontent.com/assets/17104005/16673808/6e883172-4466-11e6-871d-7fc862f644b4.JPG)

The mass of overlapping lines is known as a "spaghetti plot" in climate science; it provides a sense of the range and density of uncertainty. the beauty of the time series plot functionality is that the lines can be turned on or off, allowing the user to explore the different projections. it looks to me that there would be just enough room in the legend for the 14 plot lines. 

I would put this at a pretty high priority, but totally understand if it is out of scope for the beta version.

**Comment by joeyklee** [comment]
@cmahony we managed to get this working, but not exactly sure this is readable... Do we want to show _all_ the models? right now I've left out 2 of the models and still it is very much spaghetti.

**Comment by cmahony** [comment]
@joeyklee I think the key to managing the spaghetti factor is to have the projections only for the focal unit, as in the sketch above. another way to make it cleaner is to show the ensemble mean, but have the individual models in the legend and turned on by clicking on them. for simplicity in the beta version, i think we should just have the focal unit projections (6 models x 2 RCPs = 12 projections) in the plot.

**Comment by joeyklee** [comment]
@cmahony - for now, the easiest fix is just to keep both the focal and the comparison unit set the the same value, then only one set of lines appears.

**Comment by cmahony** [comment]
i think neither of us are happy with the spaghetti approach to the time series plot. Ultimately, i really want to be able to look at individual models in the time series, but this will take some finessing and in their current form the plots are pretty unusable... way too many lines. for the moment, i suggest we use ensemble means for each RCP. I imagine this could be calculated in the web programming, but to make things easy I have created two ensemble means csv files and uploaded them to the dropbox: 

BEC10centroid_EnsembleMean_RCP85_2011-2100MSYT.csv
BEC10centroid_EnsembleMean_RCP45_2011-2100MSYT.csv

**Comment by joeyklee** [comment]
@cmahony - cool. I'll use these vals. Will update you when the changes are made

**Comment by cmahony** [comment]
i'm thinking it will look something like this. 

![graph_timeseries_tmin_sm_idfxh1_bgxh1_simple](https://cloud.githubusercontent.com/assets/17104005/16743316/87573228-4760-11e6-9dd1-1dc2634d3172.png)

**Comment by joeyklee** [comment]
currently we now just use ensemble means
