### ISSUE TITLE
how feasible is it for me to edit the website? 

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#42]
@joeyklee, I would love to be able to edit the text for the website as i have time. How feasible is it for me to learn to do this? could i do this on github without putting the functionality of the site at risk? 

something to discuss in the next week or so.

**Comment by joeyklee** [comment]
@cmahony - it will be great for you start digging in. Are you familiar with HTML at all? It would be great for you to get working on the  `branch` --> `make changes` --> `commit` --> `sync` --> `pull request` workflow. Then I can review your changes and make sure that things don't break the code. In general though, if you're just changing text, it should be fine.

**Comment by joeyklee** [comment]
see #47
