### ISSUE TITLE
"nice-to-haves" for the beta version

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#46]
Here is a list of tweaks that would make the tool more user friendly. perhaps none of them are feasible this week, but i'm putting them out there just in case. i will add to this over time. 

**Higher priority**
- [x] BEC units are in no apparent order in the selection dropdowns. Makes it very difficult to search for the one I want. Alphabetical order would be much better. 
- [x] The pins don’t land on the map location when a unit is selected from the dropdown. 
- [x] The plot area is truncated on my laptop, and so i imagine on others too. it actually makes the tool quite unfriendly, since sometimes i can't see the legends, and other times the plot area gets stuck shifted over towards the legend. how about we have a fixed plot area that doesn't adjust width for screen size. then only the map area would be adjusted for screen size. on a related note, i don't think we need to have the retraction functionality for the plot area. I see some advantages to having it static, foremost being that the "zoom to unit" functionality of the scatterplot page would show the whole BEC map unit. 

**Lower priority**
- [x] Starting setting for the scatterplot is “map” on both axes and all points on the 1:1 line. Would be nice if the user landed on a MAT x MAP scatterplot. 
- [x] The scatterplot variable selection headings are inconsistent: “Time Aggregations: X Variable” and “X Axis: Climate Variable”. my suggestion for these is “Time Aggregations: X axis” and “Climate Element: X Axis.”
- [x] Both pins are blue on map. Would be nice if they were red and blue as on sidebar and plot
- [x] The scatterpoint legend text is “trace 0”. My suggestion is “1971-2000 normals”
- [x] The focal and comparison legend text is “ESSFdv2 RCP4.5” for the points, which isn’t correct because the points are 1971-2000 normals.  The points text could just be “ESSFdv2”. 
- [x] The large logo and “BC Climate Explorer" title text on the Map controls page take up a lot of space, forcing a scroll-down to see the map legend. I suggest that we eliminate the logo and title, and just have the “welcome to the BC climate explorer…” text. 
- [ ] The annual variables list is incomplete, and should also include all elements that are included in the seasonal list (except Tave, Tmin, Tmax, and PPT). This is my bad, as i said that you could use the default scale column in the variables csv to split them. 
- [ ] The maps would look a lot better if the log-default elements were log-scaled. With raw scaling, most of the variation in the province is just a single colour. 
- [ ] Basemap and transparency would be nice. The ClimateBC basemap is google maps, and it seems really good.

**Comment by cmahony** [comment]
@joeyklee this tool just went over the top of awesomeness. it's way better than i ever could have imagined when we got started on this. thank you so much for implementing these changes... the functionality is now at a very good beta stage IMHO, and i just need to get the text and how-to videos on there.

**Comment by joeyklee** [comment]
@cmahony woo hoo! 🎉

**Comment by cmahony** [comment]
big woo hoo. i've spent the morning having my mind blown by the information available in this tool. working on the text now. let me know if/when you have finished your functionality tweaks, then i will start work on the how-to video.

**Comment by joeyklee** [comment]
@cmahony - The major things should be in place. I don't think I'll be able to take care of those last 3 points before my trip. If I do, I'll let you know, but for now let's put them off till next time. I say: Go ahead!

**Comment by cmahony** [comment]
Ok sounds good. this tool is in great shape to send out to stakeholders. i'll start a list of post-beta (version 1.0 ??) tweaks to the existing functionality (bugs and nice-to-haves).

**Comment by joeyklee** [comment]
sounds good to me 👍 - let's close this issue then and create the list of the post beta version in a new issue. THanks!
