### ISSUE TITLE
how-to video

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bec-explorer#50]
@joeyklee can you watch [this video](https://youtu.be/1GPJwOt5yZo) and if it is acceptable could you html it into the "how to" page? i will then write around that.

**Comment by joeyklee** [comment]
@cmahony whoa!! brilliant! So great. Really nice. 

you can insert the video by putting this into the html page:

```
<iframe width="600" height="400" src="https://www.youtube.com/embed/1GPJwOt5yZo" frameborder="0" allowfullscreen></iframe>
```

you can adjust the with and the height if it looks funky. I think it will be good practice for you :)

👍

**Comment by cmahony** [comment]
@joeyklee actually ignore my request for you to put in into the how to page. i can figure out how to do that. you have better things to do!

**Comment by cmahony** [comment]
ah yes you beat me to it. thanks for the code line!
c
