### ISSUE TITLE
Scatterplot and Time series graphs

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/bec-explorer#8]
![scatterplot](https://cloud.githubusercontent.com/assets/3622055/15764325/cfabd47a-28de-11e6-9b0b-bb2710ead322.JPG)
![timeseries](https://cloud.githubusercontent.com/assets/3622055/15764326/cfd7e8b2-28de-11e6-8d31-05d03d235bfa.JPG)

**Comment by cmahony** [comment]
The axes for the scatterplot need to be transformable as appropriate to the variable. zero-limited variables such as precipitation should default to log-scale, ideally with the option to turn off log-scaling.

**Comment by joeyklee** [comment]
I'm going to close this for now - scatterplot and timeseries are working (still some bugs + need to highlight the focal and comparison unit on the scatterplot)
